name: Simple Workflow

on:
    workflow_dispatch:
      inputs:
        tags:
          description: 'Dev-school-task-input'

jobs:

    TIMESTAMP:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: 1.1 UPLOADING FILES
          run: |
            echo "${{ github.event.inputs.tags }}"
            echo "${{ github.event.inputs.tags }}" > ./.github/actions/action_1.2/tag.txt
            cp ./scripts/main.py ./.github/actions/action_1.2/main.py
        - name: 1.2 EXECUTING THE PYTHON SCRIPT
          uses: ./.github/actions/action_1.2
        - name: 1.3 DOWNLOAD ARTIFACT
          uses: actions/upload-artifact@v2
          with:
              name: log.md
              path: /home/runner/work/devops-school/devops-school/log.md
